name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      app_name:
        required: true
        type: string
      run_id:
          required: false
          type: string
          default: ${{ github.run_id }}
    outputs:
      webapp_url:
        description: URL of the deployed Azure Static Web App
        value: ${{ jobs.deploy.outputs.webapp_url }}

jobs:
  deploy:
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.retrieve_site_url.outputs.webapp_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Install SWA CLI
        run: |
          npm install -g @azure/static-web-apps-cli
          swa --version

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: artifact/
          run-id: ${{ inputs.run_id || github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: Check artifact download
        run: ls -R

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      
      - name: Deploy web app
        run: |
          swa deploy ./artifact -S ${{ secrets.AZURE_SUBSCRIPTION_ID }} --env production -n ${{ inputs.app_name }}

      - name: Get Static Web App URL
        id: retrieve_site_url
        run: |
          WEBAPP_URL=$(az staticwebapp show --name ${{ inputs.app_name }} --query "defaultHostname" --output tsv)
          echo "webapp_url=https://$WEBAPP_URL" >> $GITHUB_OUTPUT
          
    outputs:
      webapp_url: ${{ steps.retrieve_site_url.outputs.webapp_url }}
