name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      app_name:
        required: true
        type: string

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Install SWA CLI
        run: |
          npm install -g @azure/static-web-apps-cli
          swa --version

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: artifact/

      - name: Check artifact download
        run: ls -R

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      
      - name: Deploy web app
        run: |
          swa deploy ./artifact -S ${{ secrets.AZURE_SUBSCRIPTION_ID }} --env production -n ${{ inputs.app_name }}
