name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy-dev:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      app_name: swa-se-dev
    secrets: inherit

  deploy-test:
    needs: deploy-dev
    uses: ./.github/workflows/deploy.yml
    with:
      environment: test
      app_name: swa-se-test
    secrets: inherit

  deploy-prod:
    needs: deploy-test
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      app_name: swa-se-prod
    secrets: inherit