name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
      app_name:
        description: 'Name of the application'
        required: true
        type: string
        default: swa-se-dev
      run_id:
        description: 'Run ID for artifact download (optional)'
        required: true
        type: string
        default: ''

jobs:
  call-deploy-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ inputs.environment }}
      app_name: ${{ inputs.app_name }}
      run_id: ${{ inputs.run_id }}
    secrets: inherit