name: Troubleshoot

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
      app_name:
        description: 'Name of the application'
        required: true
        type: string
        default: swa-se-dev
      run_id:
        description: 'Run ID for artifact download (optional)'
        required: true
        type: string
        default: ''

jobs:
  troubleshoot:
    env:
      GH_TOKEN: ${{ github.token }}
    # environment:
    #   name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        run: |
          gh run download ${{ github.event.inputs.run_id }} -n artifact
          ls -l